### ISSUE TITLE
[Bug] "Zero Out Work Axis" should use G10 L20, not G10 L2

### ISSUE THREAD

**Issue by iceboundflame** [chilipeppr/widget-axes#4]
I am using http://chilipeppr.com/jarret and expected the below button to redefine the current work coordinate system to make the current tool position equal to zero. (That would be consistent with the other "Zero Out Temporary X Axis/Machine X Axis" buttons.)

<img width="406" alt="screen shot 2016-06-15 at 9 47 21 pm" src="https://cloud.githubusercontent.com/assets/933687/16108624/1fc1a460-3359-11e6-85d2-b89aedb1a277.png">

Instead, it sets the offset to zero, causing the current position to equal the current machine coordinates.
I think this isn't a very useful function and is unintended; the fix should simply be to use G10 L20 instead of G10 L2.

**Comment by chilipeppr** [comment]
This widget in this Github repo is for TinyG, not Grbl. The jarret workspace is really ancient now and /grbl is the one promoted on the home page of ChiliPeppr.
